# 01. Numpy 리마인드 및 컴프리헨션, 슬라이싱 연습
> 저번시간에 배운 numpy 함수들을 리마인드하고, 리스트 컴프리헨션, 슬라이싱이라는 새로운 기법을 배워봅시다.

- toc: true 
- badges: true
- comments: true
- categories: [Day 2]
- permalink: /numpy_practice
- exec: colab

이전시간에 굉장히 장황하게? 선형대수에 대해서 배웠습니다. 아마 다 머릿속에 기억하신다고 하는 건 거짓말일텐데요. 오늘은 간단하게 리마인드해보고, 새롭지만 굉장히 파워풀한 스킬인 리스트 컴프리헨션과 넘파이 슬라이싱 스킬에 대해 배워봅시다.

<br>

### 1. 이전 시간 리마인드
이전시간에는 벡터, 행렬, 텐서의 개념에 대해 배우고 numpy를 통해 이들을 계산하는 시간을 가졌습니다. 개념에 대한 내용은 집에서 스스로 복습하시고 지금 시간에는 조금더 실용적인 구현연습을 해볼까 합니다.

<br>

#### 1.1. 텐서 생성하기
이제부터 벡터, 행렬을 모두 텐서라고 부르겠습니다. 사실 벡터는 랭크가 1인 텐서, 행렬은 랭크가 2인 텐서입니다. 텐서는 이들 모두를 아우르는 말이기 때문에 여기에서부터는 벡터, 행렬과 같은 용어는 사용하지 않겠습니다. 


In [3]:
import numpy as np

ten_a = np.array([[1, 2], 
                  [3, 4]])

ten_b = np.array([[5, 6], 
                  [7, 8]])

<br>

#### 1.2. 텐서 곱하기
텐서와 텐서를 곱해봅니다. @를 사용해 곱할 수 있습니다.

In [4]:
ten_a @ ten_b

array([[19, 22],
       [43, 50]])

<br>

#### 1.3. 원소 곱하기
원소끼리만 곱을 수행할 수도 있습니다. * 를 사용해 곱할 수 있습니다.

In [5]:
ten_a * ten_b

array([[ 5, 12],
       [21, 32]])

<br>

#### 1.4. 텐서 덧셈
텐서와 텐서를 더할 땐 +, 뺄땐 -로 계산 가능합니다.

In [7]:
ten_a + ten_b

array([[ 6,  8],
       [10, 12]])

In [8]:
ten_a - ten_b

array([[-4, -4],
       [-4, -4]])

<br>

#### 1.5. 스칼라 곱
텐서에 스칼라를 곱할 땐 * 로 곱할 수 있습니다.

In [9]:
ten_a * 10

array([[10, 20],
       [30, 40]])

<br>

#### 1.6. transpose
텐서를 트랜스포즈 하려면 .T나 transpose()함수를 호출하면 됩니다.

In [10]:
ten_a

array([[1, 2],
       [3, 4]])

In [11]:
ten_a.T

array([[1, 3],
       [2, 4]])

In [12]:
ten_a.transpose(1, 0)

array([[1, 3],
       [2, 4]])

<br>

#### 1.7. reshape
reshape 함수를 사용하면 텐서의 모양이나 랭크를 바꿀 수 있습니다.

In [13]:
ten_a.reshape(1, 4)

array([[1, 2, 3, 4]])

In [14]:
ten_a.reshape(4, 1)

array([[1],
       [2],
       [3],
       [4]])

In [15]:
ten_a.reshape(2, 1, 2)

array([[[1, 2]],

       [[3, 4]]])

<br>

#### 1.8. squeeze
squeeze 함수를 사용하면 텐서에서 size가 1인 axis를 없앨 수 있습니다.

In [37]:
ten_s = np.array([[[1, 2]]])

ten_s.shape

(1, 1, 2)

In [38]:
ten_s.squeeze().shape

(2,)

<br>

#### 1.8. expand_dims
expand_dims 함수를 사용하면 원하는 위치에 size가 1인 axis를 만들 수 있습니다.

In [26]:
ten_x = np.array([[2, 3, 4], 
                  [6, 7, 8]])

ten_x.shape

(2, 3)

In [29]:
np.expand_dims(ten_x, 0).shape

(1, 2, 3)

In [30]:
np.expand_dims(ten_x, 1).shape

(2, 1, 3)

<br>

#### 1.9. concatenate
concatenate 함수를 사용하면 두 텐서를 접합시킬 수 있습니다.

In [32]:
ten_x = np.array([[2, 3, 4], 
                  [6, 7, 8]])

ten_y = np.array([[1, 2, 3], 
                  [4, 5, 6]])

In [33]:
np.concatenate([ten_x, ten_y], axis=0)

array([[2, 3, 4],
       [6, 7, 8],
       [1, 2, 3],
       [4, 5, 6]])

In [34]:
np.concatenate([ten_x, ten_y], axis=1)

array([[2, 3, 4, 1, 2, 3],
       [6, 7, 8, 4, 5, 6]])

<br>

#### 1.10. split
split 함수를 사용하면 두 텐서를 분리할 수 있습니다.

In [40]:
ten_x = np.array([[2, 3, 4], 
                  [6, 7, 8]])

In [45]:
np.split(ten_x, 2, axis=0)

[array([[2, 3, 4]]), array([[6, 7, 8]])]

In [47]:
np.split(ten_x, 3, axis=1)

[array([[2],
        [6]]),
 array([[3],
        [7]]),
 array([[4],
        [8]])]

<br>

#### 1.11. rand
random.rand 함수를 사용하면 주어진 shape에 대해 랜덤한 값으로 초기화된 텐서를 만들 수 있습니다.

In [49]:
rand_x = np.random.rand(2, 2)

rand_x

array([[0.35760383, 0.09730257],
       [0.31449127, 0.18769818]])

<br>

#### 1.12. ones
ones 함수를 사용하면 1으로 초기화된 텐서를 만들 수 있습니다. 주의할 점은 shape를 입력할때 () 괄호를 입력해야합니다.

In [50]:
ones_x = np.ones((2, 2))

ones_x

array([[1., 1.],
       [1., 1.]])

<br>

#### 1.13. zeros
zeros 함수를 사용하면 0으로 초기화된 텐서를 만들 수 있습니다. 주의할 점은 shape를 입력할때 () 괄호를 입력해야합니다.

In [52]:
zeros_x = np.zeros((2, 2))

zeros_x

array([[0., 0.],
       [0., 0.]])

<br>

#### 1.14. arange
arange 함수를 사용하면 순차적인 값으로 초기화된 벡터를 만들 수 있습니다.

In [54]:
arange_x = np.arange(10)

arange_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

<br>
    
#### 1.15. norm
norm 함수를 사용하면 텐서의 크기나 길이를 구할 수 있습니다.

In [57]:
ten_x = np.array([2, 4, 6])

In [58]:
# L1 Norm
np.linalg.norm(ten_x, ord=1)

12.0

In [59]:
# L2 Norm
np.linalg.norm(ten_x, ord=2)

7.483314773547883

In [61]:
# L3 Norm
np.linalg.norm(ten_x, ord=3)

6.603854497789253

In [63]:
ten_x = np.array([2, 4, 6])
ten_y = np.array([3, 5, 7])

In [64]:
# 두 텐서를 뺀 값의 norm을 구하면 거리를 구할 수 있습니다.

# 유클리디언 거리
np.linalg.norm(ten_x - ten_y, ord=2)

1.7320508075688772

In [65]:
# 두 텐서를 뺀 값의 norm을 구하면 거리를 구할 수 있습니다.

# 맨하탄 거리
np.linalg.norm(ten_x - ten_y, ord=1)

3.0

<br>

### 2. Numpy Slicing
이제 넘파이로 슬라이싱 하는 방법을 배워봅시다. 슬라이싱이란 주어진 데이터에서 우리가 원하는 부분만 잘라내는 것을 의미합니다.

<br>

#### 2.1. 인덱싱
인덱싱은 텐서에 인덱스를 넣어서 원하는 부분의 값을 꺼내오는 방법입니다. 파이썬 리스트와 동일한 방법으로 인덱싱 가능합니다.

In [69]:
vec_a = np.array([1, 2, 3, 4, 5])

In [70]:
vec_a[0]

1

In [71]:
vec_a[1]

2

<br>

#### 2.2. 행렬 인덱싱
랭크2 텐서인 행렬도 역시 인덱싱으로 값을 꺼낼 수 있습니다. 

In [73]:
mat_a = np.array([[1, 2, 3], 
                  [4, 5, 6]])

만약 랭크2의 행렬에 1개의 인덱스를 붙이면 다음과 같이 반환됩니다.

In [76]:
mat_a[0]

array([1, 2, 3])

In [77]:
mat_a[1]

array([4, 5, 6])

<br>

인덱스를 두개 붙일 땐 콤마(,)로 구분합니다. 이 경우 정확하게 하나의 엘리먼트를 선택할 수 있습니다. 앞선 인덱스는 행, 뒤의 인덱스는 열을 의미합니다.

In [81]:
mat_a[0, 0] # 행:0, 열:0

1

In [91]:
mat_a[1, 0] # 행:1, 열:0

4

<br>

#### 2.3. 슬라이싱
콜론(:)을 이용하면 범위를 선택할 수 있습니다.

In [100]:
vec_a = np.array([1, 2, 3, 4, 5])

In [101]:
vec_a[0: 1] # 0 ~ 1이전까지

array([1])

In [102]:
vec_a[0: 2] # 0 ~ 2이전까지

array([1, 2])

In [103]:
vec_a[0: 3] # 0 ~ 2이전까지

array([1, 2, 3])

In [104]:
vec_a[1: 3] # 1 ~ 3이전까지

array([2, 3])

<br>

만약 n부터 끝까지 선택하려면 n : 과 같이 끝을 비우면 됩니다.

In [90]:
mat_a[0, 0 :] # 행:0, 열:0 ~ 끝까지

array([1, 2, 3])

In [92]:
mat_a[0, 1 :] # 행:0, 열:1 ~ 끝까지

array([2, 3])

In [93]:
mat_a[0, 2 :] # 행:0, 열:0 ~ 끝까지

array([3])

<br>

만약 0부터 n까지 선택하려면  : n 과 같이 앞을 비우면 됩니다.

In [97]:
mat_a[0, :1] # 행:0, 열:0 ~ 끝까지

array([1])

In [98]:
mat_a[0, :2] # 행:0, 열:0 ~ 끝까지

array([1, 2])

In [99]:
mat_a[0, :3] # 행:0, 열:0 ~ 끝까지

array([1, 2, 3])